# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-28 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_email', models.EmailField(max_length=254, verbose_name='email')),
                ('msg_message', models.TextField(verbose_name='message')),
                ('msg_status', models.BooleanField(verbose_name='status')),
            ],
        ),
    ]
